# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7122a393568640cb566cd491ade0d633acb4b1156f4573072a15790bde4118040aa96eeda44388d91cc98435e1860e638b82603c4c175c3a45c1f22bacace032

test:
  secret_key_base: f0e7734b3fa430e2baa4a35eb425896c7dbfc6ff7264a8e087cc66b1b1c07ed00c4cb1ff6f11929f36483f56a595877a283e792c9c100f813ddd6333bf19c155

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
